language: python
python:
    - "3.8"
services:
    - mysql
install:
    - pip install -r api/requirements.txt
before-script:
    - mysql -e "CREATE USER 'dongeonguard' IDENTIFIED BY 'SuchWow'"
    - mysql -e "CREATE DATABASE imagedongeon; GRANT ALL PRIVILEGES ON imagedongeon.* TO dongeonguard;"
    - mysql -e "USE imagedongeon; CREATE TABLE imagedongeon ( id BIGINT NOT NULL AUTO_INCREMENT, md5_hash TEXT NOT NULL, tags MEDIUMTEXT NOT NULL, post_time INT NOT NULL, height INT NOT NULL, width INT NOT NULL, rating TEXT, image LONGBLOB NOT NULL, PRIMARY KEY (id) );"
script: python3 api/api.py & cd api & pytest