language: python
python:
    - "3.8"
addons:
    mariadb: '10.0'      
install:
    - pip install -r requirements.txt
before-script:
    - mysql -e "CREATE USER 'dongeonguard' IDENTIFIED BY 'SuchWow'"
    - mysql -e "CREATE DATABASE imagedongeon; GRANT ALL PRIVILEGES ON imagedongeon.* TO dongeonguard;"
    - mysql -e "USE imagedongeon; CREATE TABLE \`posts\` ( \`post_id\` INT NOT NULL AUTO_INCREMENT, \`md5_hash\` TEXT NOT NULL, \`post_time\` INT NOT NULL, \`height\` INT NOT NULL, \`width\` INT NOT NULL, \`rating\` TEXT, \`image\` LONGBLOB NOT NULL, PRIMARY KEY (\`post_id\`));"
    - mysql -e "USE imagedongeon; CREATE TABLE \`tags\` (\`tag_id\` INT NOT NULL AUTO_INCREMENT, \`name\` TEXT NOT NULL, \`description\` TEXT NOT NULL, PRIMARY KEY (\`tag_id\`));"
    - mysql -e "USE imagedongeon; CREATE TABLE \`post_tag_map\` (\`post_id\` INT NOT NULL, \`tag_id\` INT NOT NULL, PRIMARY KEY (\`post_id\`,\`tag_id\`), KEY \`tag_fk\` (\`tag_id\`), CONSTRAINT \`image_fk\` FOREIGN KEY (\`post_id\`) REFERENCES \`posts\` (\`post_id\`), CONSTRAINT \`tag_fk\` FOREIGN KEY (\`tag_id\`) REFERENCES \`tags\` (\`tag_id\`));"
    - mysql -e "USE imagedongeon; CREATE TABLE \`settings\` ( id BIGINT NOT NULL AUTO_INCREMENT, \`key\` TEXT, \`value\` TEXT, PRIMARY KEY (id));"
script: python3 main.py & pytest