version: '3'
services: 
    sql:
        image: mariadb
        restart: unless-stopped
        environment: 
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
        ports: 
            - "3306:3306"
        volumes: 
            - sqldata:/var/lib/mysql
volumes:
    sqldata: